-- MySQL Script generated by MySQL Workbench
-- mar 17 nov 2020 10:18:37 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema supercomprin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema supercomprin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `supercomprin` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `supercomprin`.`wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supercomprin`.`wallet` (
  `idwallet` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `fechanacimiento` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `puntos` INT UNSIGNED NOT NULL DEFAULT '0',
  `saldo` INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`idwallet`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `supercomprin`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supercomprin`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `puntos` INT UNSIGNED NOT NULL,
  `precio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`devolucion` (
  `iddevolucion` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `idwallet` INT NOT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`iddevolucion`),
  INDEX `fk_devolucion_wallet_idx` (`idwallet` ASC),
  INDEX `fk_devolucion_producto1_idx` (`idproducto` ASC),
  CONSTRAINT `fk_devolucion_wallet`
    FOREIGN KEY (`idwallet`)
    REFERENCES `supercomprin`.`wallet` (`idwallet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_devolucion_producto1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `supercomprin`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `supercomprin` ;

-- -----------------------------------------------------
-- Table `supercomprin`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supercomprin`.`compra` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NOT NULL,
  `idwallet` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `fk_COMPRA_WALLET` (`idwallet` ASC),
  INDEX `fk_COMPRA_PRODUCTO` (`idproducto` ASC),
  CONSTRAINT `fk_COMPRA_PRODUCTO`
    FOREIGN KEY (`idproducto`)
    REFERENCES `supercomprin`.`producto` (`idproducto`),
  CONSTRAINT `fk_COMPRA_WALLET`
    FOREIGN KEY (`idwallet`)
    REFERENCES `supercomprin`.`wallet` (`idwallet`))
ENGINE = InnoDB
AUTO_INCREMENT = 387
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
