-- MySQL Script generated by MySQL Workbench
-- Tue Nov 17 19:34:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema supercomprin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema supercomprin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `supercomprin` DEFAULT CHARACTER SET utf8 ;
USE `supercomprin` ;

DROP TABLE `supercomprin`.`producto`;
DROP TABLE `supercomprin`.`wallet`;
DROP TABLE `supercomprin`.`devolucion`;
DROP TABLE `supercomprin`.`compra`;
-- -----------------------------------------------------
-- Table `supercomprin`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supercomprin`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `puntos` INT UNSIGNED NOT NULL,
  `precio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `supercomprin`.`wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supercomprin`.`wallet` (
  `idwallet` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `dni` VARCHAR(9) NOT NULL UNIQUE,
  `fechanacimiento` DATE NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `puntos` INT UNSIGNED NOT NULL DEFAULT '0',
  `saldo` INT UNSIGNED NOT NULL DEFAULT '0',
  `edad` INT NULL DEFAULT NULL,
  CHECK (edad>=18),
  PRIMARY KEY (`idwallet`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;



-- -----------------------------------------------------
-- Table `supercomprin`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supercomprin`.`compra` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NOT NULL,
  `idwallet` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `fk_COMPRA_WALLET` (`idwallet` ASC) VISIBLE,
  INDEX `fk_COMPRA_PRODUCTO` (`idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_COMPRA_PRODUCTO`
    FOREIGN KEY (`idproducto`)
    REFERENCES `supercomprin`.`producto` (`idproducto`),
  CONSTRAINT `fk_COMPRA_WALLET`
    FOREIGN KEY (`idwallet`)
    REFERENCES `supercomprin`.`wallet` (`idwallet`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `supercomprin`.`devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supercomprin`.`devolucion` (
  `iddevolucion` INT NOT NULL AUTO_INCREMENT,
  `idcompra` INT NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`iddevolucion`),
  INDEX `fk_devolucion_compra` (`idcompra` ASC) VISIBLE,
  CONSTRAINT `fk_devolucion_compra`
    FOREIGN KEY (`idcompra`)
    REFERENCES `supercomprin`.`compra` (`idcompra`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;

INSERT INTO wallet (nombre,apellidos,dni,fechanacimiento,email,puntos,saldo,edad) VALUES ("Axel","Perez","54658745a","1988-06-28","axel@sdfh",default,default,DATEDIFF( current_date(),"1988-06-28")/365);
INSERT INTO wallet (nombre,apellidos,dni,fechanacimiento,email,puntos,saldo,edad) VALUES ("Luis","Garcia","78451236b","1995-11-27","luisga@sdg",default,default,DATEDIFF( current_date(),"1995-11-27")/365);
INSERT INTO wallet (nombre,apellidos,dni,fechanacimiento,email,puntos,saldo,edad) VALUES ("Aisha","Flordelis","78451202c","1990-12-24","aisha@sdfs",default,default,DATEDIFF( current_date(),"1990-12-24")/365);
INSERT INTO wallet (nombre,apellidos,dni,fechanacimiento,email,puntos,saldo,edad) VALUES ("Ana","Gonzalez","78451245d","2001-05-17","ana@hfh",default,default,DATEDIFF( current_date(),"2001-05-17")/365);
INSERT INTO wallet (nombre,apellidos,dni,fechanacimiento,email,puntos,saldo,edad) VALUES ("Luis","Perez","54658745e","1988-06-28","axel@sdfh",default,default,DATEDIFF( current_date(),"1988-06-28")/365);
INSERT INTO wallet (nombre,apellidos,dni,fechanacimiento,email,puntos,saldo,edad) VALUES ("Amparo","Garcia","78451236f","1995-11-27","luisga@sdg",default,default,DATEDIFF( current_date(),"1995-11-27")/365);
INSERT INTO wallet (nombre,apellidos,dni,fechanacimiento,email,puntos,saldo,edad) VALUES ("Lucia","Flordelis","78451202g","1990-12-24","aisha@sdfs",default,default,DATEDIFF( current_date(),"1990-12-24")/365);
INSERT INTO wallet (nombre,apellidos,dni,fechanacimiento,email,puntos,saldo,edad) VALUES ("Josefa","Gonzalez","78451245h","2001-05-17","ana@hfh",default,default,DATEDIFF( current_date(),"2001-05-17")/365);   
INSERT INTO wallet (nombre,apellidos,dni,fechanacimiento,email,puntos,saldo,edad) VALUES ("Pepito","Perez","54658745i","1988-06-28","axel@sdfh",default,default,DATEDIFF( current_date(),"1988-06-28")/365);
INSERT INTO wallet (nombre,apellidos,dni,fechanacimiento,email,puntos,saldo,edad) VALUES ("Kevin","Garcia","78451236j","1995-11-27","luisga@sdg",default,default,DATEDIFF( current_date(),"1995-11-27")/365);
INSERT INTO wallet (nombre,apellidos,dni,fechanacimiento,email,puntos,saldo,edad) VALUES ("Hector","Flordelis","78451202k","1990-12-24","aisha@sdfs",default,default,DATEDIFF( current_date(),"1990-12-24")/365);
INSERT INTO wallet (nombre,apellidos,dni,fechanacimiento,email,puntos,saldo,edad) VALUES ("Jose","Gonzalez","78451245l","2001-05-17","ana@hfh",default,default,DATEDIFF( current_date(),"2001-05-17")/365); 
    
INSERT INTO producto (nombre, puntos, precio) VALUES ("Jarrón",1,5);
INSERT INTO producto (nombre, puntos, precio) VALUES ("Televisor",10,100);
INSERT INTO producto (nombre, puntos, precio) VALUES ("Chaqueta",5,50);
INSERT INTO producto (nombre, puntos, precio) VALUES ("Gorra",1,3);
INSERT INTO producto (nombre, puntos, precio) VALUES ("Sofa",50,500);         
INSERT INTO producto (nombre, puntos, precio) VALUES ("Chicles",1,5);
INSERT INTO producto (nombre, puntos, precio) VALUES ("Impresora",10,100);
INSERT INTO producto (nombre, puntos, precio) VALUES ("Microondas",5,50);
INSERT INTO producto (nombre, puntos, precio) VALUES ("Kinder",1,3);
INSERT INTO producto (nombre, puntos, precio) VALUES ("Estanteria",50,500);          
INSERT INTO producto (nombre, puntos, precio) VALUES ("Macarrones",1,10);
INSERT INTO producto (nombre, puntos, precio) VALUES ("Vino",6,60);
INSERT INTO producto (nombre, puntos, precio) VALUES ("Tomates",1,1);
INSERT INTO producto (nombre, puntos, precio) VALUES ("Lechuga",1,10);
INSERT INTO producto (nombre, puntos, precio) VALUES ("Patatas",1,2);   
            
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
