-- MySQL Script generated by MySQL Workbench
-- Sat Nov 14 19:01:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema supercomprin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema supercomprin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `supercomprin` DEFAULT CHARACTER SET utf8 ;
USE `supercomprin` ;

-- -----------------------------------------------------
-- Table `supercomprin`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supercomprin`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `puntos` INT UNSIGNED NOT NULL,
  `precio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `supercomprin`.`wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supercomprin`.`wallet` (
  `idwallet` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `fechanacimiento` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `puntos` INT UNSIGNED NOT NULL DEFAULT '0',
  `saldo` INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`idwallet`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `supercomprin`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supercomprin`.`compra` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NOT NULL,
  `idwallet` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `fk_COMPRA_WALLET` (`idwallet` ASC) VISIBLE,
  INDEX `fk_COMPRA_PRODUCTO` (`idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_COMPRA_PRODUCTO`
    FOREIGN KEY (`idproducto`)
    REFERENCES `supercomprin`.`producto` (`idproducto`),
  CONSTRAINT `fk_COMPRA_WALLET`
    FOREIGN KEY (`idwallet`)
    REFERENCES `supercomprin`.`wallet` (`idwallet`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

INSERT INTO wallet (nombre,apellidos,dni,fechanacimiento,email) VALUES ("Axel","Perez","54658745y","28-06-1988","axel@sdfh");
INSERT INTO wallet (nombre,apellidos,dni,fechanacimiento,email) VALUES ("Luis","Garcia","78451236u","27-11-1995","luisga@sdg");
INSERT INTO wallet (nombre,apellidos,dni,fechanacimiento,email) VALUES ("Aisha","Flordelis","78451202p","24-12-1990","aisha@sdfs");
INSERT INTO wallet (nombre,apellidos,dni,fechanacimiento,email) VALUES ("Ana","Gonzalez","78451245l","17-05-2001","ana@hfh");
        
INSERT INTO producto (nombre, puntos, precio) VALUES ("Jarrón",1,5);
INSERT INTO producto (nombre, puntos, precio) VALUES ("Televisor",10,100);
INSERT INTO producto (nombre, puntos, precio) VALUES ("Chaqueta",5,50);
INSERT INTO producto (nombre, puntos, precio) VALUES ("Gorra",1,3);
INSERT INTO producto (nombre, puntos, precio) VALUES ("Sofa",50,500);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
